# Site settings
title: Your Name
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"

# Contact info
gravatar_hash:     "00000000000000000000000000000000"
twitter_username:  yourname
facebook_username: yourname
github_username:   yourname
linkedin_profile:  "https://www.linkedin.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
